host:
host_port: # This is the port of the panel (optional)
port: 9531 # This is tge standard port for the exporter
api_key: 
https: true
ignore_ssl: false
# Can be set to `admin-all` (return all servers), `owner` (only owned servers)
# or "" (only accessible servers, shown in your servers list)
server_list_type: owner
query_interval: 10
# Interval in seconds between each query to the Pterodactyl panel (default: 10)
